plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qujindai.localvideo'
    compileSdk 35

    defaultConfig {
        applicationId 'com.qujindai.localvideo'
        minSdk 28
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
            keepDebugSymbols += ['**/librife.so']
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
