#include <jni.h>
#include <android/log.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>
#include "mnn_runtime.hpp"
namespace {
constexpr const char* kTag="MobileI2VGpu";constexpr size_t kW=1280,kH=720,kT=17,kSingle=128*3*23*40,kGuide=128*23*40,kCfg=2*kSingle,kImage=3*kH*kW,kPrompt=2*300*896,kCond=3*23*40,kGuidePlane=23*40,kTextMask=300,kDecoded=3*kT*kH*kW,kPixels=kH*kW;
struct RuntimeHandle{mobilei2v::OpenClSession encoder,denoiser,decoder;std::vector<float> prompt,cond,decoded;std::vector<uint8_t> mask;};std::mutex gMutex;std::unordered_map<jlong,std::unique_ptr<RuntimeHandle>> gHandles;jlong gNext=1;
std::string str(JNIEnv* e,jstring v){if(!v)return{};const char* c=e->GetStringUTFChars(v,nullptr);if(!c)return{};std::string s(c);e->ReleaseStringUTFChars(v,c);return s;}jstring js(JNIEnv*e,const std::string&s){return e->NewStringUTF(s.c_str());}
float h2f(uint16_t v){uint32_t sign=static_cast<uint32_t>(v&0x8000u)<<16u,ex=(v>>10u)&0x1fu,m=v&0x3ffu,b;if(ex==0){if(m==0)b=sign;else{int sh=0;while((m&0x400u)==0){m<<=1u;++sh;}m&=0x3ffu;b=sign|(static_cast<uint32_t>(127-15-sh+1)<<23u)|(m<<13u);}}else if(ex==0x1fu)b=sign|0x7f800000u|(m<<13u);else b=sign|((ex+112u)<<23u)|(m<<13u);float o;std::memcpy(&o,&b,4);return o;}
bool readPrompt(const std::string&p,std::vector<float>&o){std::ifstream s(p,std::ios::binary|std::ios::ate);if(!s||s.tellg()!=static_cast<std::streamsize>(kPrompt*2))return false;s.seekg(0);std::vector<uint16_t> h(kPrompt);if(!s.read(reinterpret_cast<char*>(h.data()),static_cast<std::streamsize>(h.size()*2)))return false;o.resize(kPrompt);for(size_t i=0;i<kPrompt;i++){o[i]=h2f(h[i]);if(!std::isfinite(o[i]))return false;}return true;}
bool readMask(const std::string&p,std::vector<uint8_t>&o){std::ifstream s(p,std::ios::binary|std::ios::ate);if(!s||s.tellg()!=static_cast<std::streamsize>(kTextMask))return false;s.seekg(0);o.resize(kTextMask);return static_cast<bool>(s.read(reinterpret_cast<char*>(o.data()),kTextMask));}
bool exp(MNN::Interpreter*i,MNN::Session*s,const char*n,size_t c,bool out=false){auto*t=out?i->getSessionOutput(s,n):i->getSessionInput(s,n);return t&&static_cast<size_t>(t->elementSize())==c;}
bool valid(const RuntimeHandle&h){return h.encoder&&h.denoiser&&h.decoder&&exp(h.encoder.interpreter.get(),h.encoder.session,"image",kImage)&&exp(h.encoder.interpreter.get(),h.encoder.session,"latent",kGuide,true)&&exp(h.denoiser.interpreter.get(),h.denoiser.session,"latent",kCfg)&&exp(h.denoiser.interpreter.get(),h.denoiser.session,"timestep",2)&&exp(h.denoiser.interpreter.get(),h.denoiser.session,"prompt",kPrompt)&&exp(h.denoiser.interpreter.get(),h.denoiser.session,"cond_mask",kCond)&&exp(h.denoiser.interpreter.get(),h.denoiser.session,"text_mask",kTextMask)&&exp(h.denoiser.interpreter.get(),h.denoiser.session,"flow_score",2)&&exp(h.denoiser.interpreter.get(),h.denoiser.session,"output",kCfg,true)&&exp(h.decoder.interpreter.get(),h.decoder.session,"latent",kSingle)&&exp(h.decoder.interpreter.get(),h.decoder.session,"video",kDecoded,true);}
std::unique_ptr<RuntimeHandle> create(const std::string&d){auto h=std::make_unique<RuntimeHandle>();if(!readPrompt(d+"/empty_prompt.f16",h->prompt)||!readMask(d+"/empty_prompt_mask.bin",h->mask))return nullptr;h->cond.assign(kCond,0.f);std::fill(h->cond.begin(),h->cond.begin()+kGuidePlane,1.f);h->encoder=mobilei2v::createOpenClSession(d+"/vae_encoder.mnn",d,"vae-encoder-opencl.cache");h->denoiser=mobilei2v::createOpenClSession(d+"/denoiser.mnn",d,"denoiser-opencl.cache");h->decoder=mobilei2v::createOpenClSession(d+"/vae_decoder.mnn",d,"vae-decoder-opencl.cache");return valid(*h)?std::move(h):nullptr;}RuntimeHandle* get(jlong id){auto i=gHandles.find(id);return i==gHandles.end()?nullptr:i->second.get();}
}
extern "C" JNIEXPORT jstring JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeProbe(JNIEnv*e,jclass,jstring dv){std::string d=str(e,dv);auto h=d.empty()?nullptr:create(d);if(!h)return js(e,"NOT_READY:MNN OpenCL full graph contract failed");bool c=!h->encoder.cacheFile.empty()&&!h->denoiser.cacheFile.empty()&&!h->decoder.cacheFile.empty();return js(e,c?"MNN_OPENCL_READY:cache-enabled":"MNN_OPENCL_READY:cache-disabled");}
extern "C" JNIEXPORT jlong JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeLoad(JNIEnv*e,jclass,jstring dv){std::string d=str(e,dv);auto h=d.empty()?nullptr:create(d);if(!h)return 0;std::lock_guard<std::mutex>g(gMutex);jlong id=gNext++;gHandles.emplace(id,std::move(h));return id;}
extern "C" JNIEXPORT jint JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeEncode(JNIEnv*e,jclass,jlong id,jfloatArray iv,jfloatArray gv){std::lock_guard<std::mutex>g(gMutex);auto*h=get(id);if(!h)return-1;if(!iv||e->GetArrayLength(iv)!=static_cast<jsize>(kImage)||!gv||e->GetArrayLength(gv)!=static_cast<jsize>(kGuide))return-2;jfloat*in=e->GetFloatArrayElements(iv,nullptr);if(!in)return-3;bool ok=mobilei2v::copyFloatInput(h->encoder.interpreter.get(),h->encoder.session,"image",in,kImage);e->ReleaseFloatArrayElements(iv,in,JNI_ABORT);if(!ok||h->encoder.interpreter->runSession(h->encoder.session)!=0)return-4;jfloat*out=e->GetFloatArrayElements(gv,nullptr);if(!out)return-5;ok=mobilei2v::copyFloatOutput(h->encoder.interpreter.get(),h->encoder.session,"latent",out,kGuide);e->ReleaseFloatArrayElements(gv,out,ok?0:JNI_ABORT);return ok?0:-6;}
extern "C" JNIEXPORT jint JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeRunDenoiser(JNIEnv*e,jclass,jlong id,jfloatArray lv,jfloat tv,jfloatArray fv,jfloatArray ov){std::lock_guard<std::mutex>g(gMutex);auto*h=get(id);if(!h)return-1;if(!lv||e->GetArrayLength(lv)!=static_cast<jsize>(kCfg)||!fv||e->GetArrayLength(fv)!=2||!ov||e->GetArrayLength(ov)!=static_cast<jsize>(kCfg))return-2;jfloat*l=e->GetFloatArrayElements(lv,nullptr),*f=e->GetFloatArrayElements(fv,nullptr);if(!l||!f){if(l)e->ReleaseFloatArrayElements(lv,l,JNI_ABORT);if(f)e->ReleaseFloatArrayElements(fv,f,JNI_ABORT);return-3;}float t[2]={tv,tv};bool ok=mobilei2v::copyFloatInput(h->denoiser.interpreter.get(),h->denoiser.session,"latent",l,kCfg)&&mobilei2v::copyFloatInput(h->denoiser.interpreter.get(),h->denoiser.session,"timestep",t,2)&&mobilei2v::copyFloatInput(h->denoiser.interpreter.get(),h->denoiser.session,"prompt",h->prompt.data(),kPrompt)&&mobilei2v::copyFloatInput(h->denoiser.interpreter.get(),h->denoiser.session,"cond_mask",h->cond.data(),kCond)&&mobilei2v::copyUint8Input(h->denoiser.interpreter.get(),h->denoiser.session,"text_mask",h->mask.data(),kTextMask)&&mobilei2v::copyFloatInput(h->denoiser.interpreter.get(),h->denoiser.session,"flow_score",f,2);e->ReleaseFloatArrayElements(lv,l,JNI_ABORT);e->ReleaseFloatArrayElements(fv,f,JNI_ABORT);if(!ok)return-4;int code=h->denoiser.interpreter->runSession(h->denoiser.session);if(code!=0){__android_log_print(ANDROID_LOG_ERROR,kTag,"denoiser run failed %d",code);return-5;}jfloat*out=e->GetFloatArrayElements(ov,nullptr);if(!out)return-6;ok=mobilei2v::copyFloatOutput(h->denoiser.interpreter.get(),h->denoiser.session,"output",out,kCfg);e->ReleaseFloatArrayElements(ov,out,ok?0:JNI_ABORT);return ok?0:-7;}
extern "C" JNIEXPORT jint JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeDecode(JNIEnv*e,jclass,jlong id,jfloatArray lv){std::lock_guard<std::mutex>g(gMutex);auto*h=get(id);if(!h)return-1;if(!lv||e->GetArrayLength(lv)!=static_cast<jsize>(kSingle))return-2;jfloat*l=e->GetFloatArrayElements(lv,nullptr);if(!l)return-3;bool ok=mobilei2v::copyFloatInput(h->decoder.interpreter.get(),h->decoder.session,"latent",l,kSingle);e->ReleaseFloatArrayElements(lv,l,JNI_ABORT);if(!ok||h->decoder.interpreter->runSession(h->decoder.session)!=0)return-4;h->decoded.assign(kDecoded,0.f);ok=mobilei2v::copyFloatOutput(h->decoder.interpreter.get(),h->decoder.session,"video",h->decoded.data(),kDecoded);if(!ok){h->decoded.clear();return-5;}return 0;}
extern "C" JNIEXPORT jint JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeCopyDecodedFrameArgb(JNIEnv*e,jclass,jlong id,jint frame,jintArray av){std::lock_guard<std::mutex>g(gMutex);auto*h=get(id);if(!h||h->decoded.size()!=kDecoded)return-1;if(frame<0||frame>=static_cast<jint>(kT)||!av||e->GetArrayLength(av)!=static_cast<jsize>(kPixels))return-2;jint*a=e->GetIntArrayElements(av,nullptr);if(!a)return-3;size_t plane=kH*kW,t=static_cast<size_t>(frame);for(size_t i=0;i<plane;i++){int rgb[3];for(size_t c=0;c<3;c++){float v=std::clamp(h->decoded[(c*kT+t)*plane+i],-1.f,1.f);rgb[c]=static_cast<int>(std::lround((v+1.f)*127.5f));}a[i]=static_cast<jint>(0xff000000u|(static_cast<uint32_t>(rgb[0])<<16u)|(static_cast<uint32_t>(rgb[1])<<8u)|static_cast<uint32_t>(rgb[2]));}e->ReleaseIntArrayElements(av,a,0);return 0;}
extern "C" JNIEXPORT void JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeClearDecoded(JNIEnv*,jclass,jlong id){std::lock_guard<std::mutex>g(gMutex);if(auto*h=get(id))std::vector<float>().swap(h->decoded);}
extern "C" JNIEXPORT void JNICALL Java_com_qujindai_localvideo_MobileI2VGpuNative_nativeRelease(JNIEnv*,jclass,jlong id){std::lock_guard<std::mutex>g(gMutex);gHandles.erase(id);}
